"""initial migration

Revision ID: 54d126c7ee5f
Revises: ffd6368cb2bc
Create Date: 2016-06-07 17:15:26.582565

"""

# revision identifiers, used by Alembic.
revision = '54d126c7ee5f'
down_revision = 'ffd6368cb2bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
