"""initial migration

Revision ID: bc4da0b0a620
Revises: None
Create Date: 2016-02-21 18:43:01.333648

"""

# revision identifiers, used by Alembic.
revision = 'bc4da0b0a620'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    ### end Alembic commands ###
